version: "3.8"

services:
  todo-app:
    container_name: todo-app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=todo-database
      - MYSQL_USER=todo-user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=todo
    ports:
      - "3000:3000"
    networks:
      - todo-network
    restart: on-failure
    depends_on:
      - todo-database

  todo-database:
    container_name: todo-database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo-user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3000"
    networks:
      - todo-network

networks:
  todo-network:

